<?php

/**
 * @file
 * Contains custom_404_redirect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_404_redirect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_404_redirect module.
    case 'help.page.custom_404_redirect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is to catch 404 and redirect to custom page') . '</p>';
      return $output;

    default:
  }
}
